sudo: false
language: go

go:
    1.15.x

go_import_path: github.com/snhilde/getcast

env:
    GO111MODULE=on

install:
    - go mod download
    - go get golang.org/x/lint/golint
    - go install golang.org/x/lint/golint

script:
    - make fmt-check
    - make lint-check
    - make test
